### ISSUE TITLE
Python Version Problem?

### ISSUE THREAD

**Issue by Satvik2101** [nikkhil13/Python_scripts_for_automation#1]
I ran the torrent downloader script and there were problems with 'missing parenthesis to call print' and 'raw_input' which I fixed, assuming there was something wrong with the python version.
I ran it again , it asked me the torrent, gave me the list , I typed in the number and then I got this error message:
`Traceback (most recent call last):
  File "C:\Users\Satvik\Downloads\torrent_downloader.py", line 122, in <module>
    begin_here(url)
  File "C:\Users\Satvik\Downloads\torrent_downloader.py", line 118, in begin_here
    start_download(href[int(torrent_no)-1])
  File "C:\Users\Satvik\Downloads\torrent_downloader.py", line 41, in start_download
    output.write(link)
TypeError: a bytes-like object is required, not 'str'`
I have no idea what this is, please help.

**Comment by nikkhil13** [comment]
Yes, this is an error due to Python version. I guess you are using python 3.x.
Try changing the line - 
```
	with open('test.txt','wb') as output:
	 	output.write(link)
```
to
```
	with open('test.txt','w') as output:
	 	output.write(link)
```

**Comment by Satvik2101** [comment]
Thanks, it worked.
